{% set name = "nceplibs-ip" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-ip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 858d9201ce0bc4d16b83581ef94a4a0262f498ed1ea1b0535de2e575da7a8b8c

build:
  number: 3

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}        # [not win]
    - make                       # [not win]
    - m2w64-gcc-fortran          # [win]
    - ninja                      # [win]
    - cmake
    - pkg-config >=0.21
  host:
    - llvm-openmp                # [osx]
    - libgomp                    # [linux]
    - nceplibs-sp >=2.3.0
    - m2w64-gcc-fortran          # [win]
  run:
    - llvm-openmp                # [osx]
    - libgomp                    # [linux]
    - nceplibs-sp >=2.3.0
    - m2w64-gcc-libgfortran      # [win]
    - m2w64-gcc-libs             # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libip_4${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libip_d${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\libip_4.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libip_d.dll exit 1  # [win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-ip
  summary: The NCEP interpolation library contains Fortran 90 subprograms used for interpolating between nearly all grids used at NCEP.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EricEngle-NOAA
    - TimothyCera-NOAA
