{% set name = "nceplibs-ip" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-ip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5279f11f4c12db68ece74cec392b7a2a6b5166bc505877289f34cc3149779619
  patches:
    - 0001-Configure-flags-for-Intel-and-gfortran.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - make                             # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - ninja                            # [win]
    - cmake
    - pkg-config >=0.21
  host:
    - libgomp      # [linux]
    - llvm-openmp
  run:
    - libgomp      # [linux]
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/lib/libip_4${SHLIB_EXT}       # [not win]
    - test -f ${PREFIX}/lib/libip_d${SHLIB_EXT}       # [not win]
    - if not exist %LIBRARY_BIN%\\libip_4.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libip_d.dll exit 1  # [win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-ip
  summary: The NCEP interpolation library contains Fortran 90 subprograms used for interpolating between nearly all grids used at NCEP.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EricEngle-NOAA
    - TimothyCera-NOAA
