build_platform:
  linux_64: linux_64
  osx_64: osx_64
  osx_arm64: osx_64
  win_64: win_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  osx_arm64: azure
test_on_native_only: true
